name: Project959
favicon: null
layout_spectrum: 0.90024
typography_spectrum: 0.4397
title: Project959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1f3fd'
    - '#070206'
    - '#56483f'
    - '#94bc38'
    - '#6b8555'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
