name: Project959
favicon: null
layout_spectrum: 0.90024
typography_spectrum: 0.4397
title: Project959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.699708080617711
  lightness: 0.973234205506742
  saturation: 0.3639810555614531
  rhythmicContrast: 0.6089123177807778
purpose: []
